### Day1

#### Problem 1: Create and Inspect a Sales Array

* Task: You have sales data for a week in a Python list. Convert this list into a NumPy array and print its shape, number of dimensions, total size, and data type.

* Test Case:

* Input: sales_data = [150.5, 165.2, 142.0, 178.5, 191.0, 160.8, 155.3]

Expected Output:

   * Shape: (7,)
    
   * Ndim: 1
    
   * Size: 7
    
   * Dtype: float64

In [1]:
import numpy as np
sales_data =np.array([150.5, 165.2, 142.0, 178.5, 191.0, 160.8, 155.3])
print(sales_data.shape)
print(sales_data.ndim)
print(sales_data.size)
print(sales_data.dtype)

(7,)
1
7
float64


### Problem 2: Initialize a Blank Scoreboard

* Task: Create a 10x4 NumPy array to represent a scoreboard for 10 players in 4 rounds of a game. Initialize all scores to zero.

* Test Case:

* Input: None

* Expected Output: A 10x4 NumPy array where every element is 0.

In [3]:
np.zeros((10,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Problem 3: Generate a Sequence of Years

* Task: Create a NumPy array containing all the years from 2000 to 2024, inclusive.

* Test Case:

* Input: None

* Expected Output: [2000, 2001, 2002, ..., 2023, 2024]

In [4]:
years = np.arange(2000,2025)
print(years)

[2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013
 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024]


### Problem 4: Default Configuration Matrix

* Task: Create a 5x5 matrix where every value is 1. This could represent a default configuration or a mask in image processing.

* Test Case:

* Input: None

* Expected Output: A 5x5 NumPy array where every element is 1.

In [5]:
ones = np.ones((5,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Problem 5: Simulate Sensor Readings

* Task: A sensor takes 100 readings that should be between 0 and 1. Create a 1D NumPy array of size 100 with random floats to simulate these readings.

* Test Case:

* Input: None

* Expected Output: A 1D NumPy array with 100 random floats, where each float is between 0.0 and 1.0.

In [9]:
randoms = np.random.rand(100)
print(randoms)

[0.97913718 0.45126595 0.53218536 0.64502481 0.56939309 0.80195499
 0.07293995 0.16583319 0.62701826 0.71814708 0.69053912 0.94245927
 0.77211037 0.41979605 0.97030926 0.88467123 0.17793842 0.79181168
 0.85449063 0.79479632 0.31288042 0.88489634 0.58386875 0.35071593
 0.27623679 0.83520428 0.53120411 0.86484845 0.82540057 0.28345026
 0.39465281 0.58882042 0.57755951 0.30188784 0.5110748  0.81416239
 0.55631928 0.35170619 0.34711965 0.8179681  0.06288772 0.29479933
 0.88785016 0.30849976 0.41905077 0.96159244 0.75314508 0.59385691
 0.70053251 0.23701924 0.76137205 0.37906516 0.78553673 0.56967247
 0.9998072  0.05169826 0.41156588 0.92871173 0.75742746 0.46535575
 0.00813217 0.83148019 0.4579392  0.79662308 0.56475036 0.42410877
 0.47524109 0.8622031  0.4749548  0.72305869 0.86631215 0.88463656
 0.60113709 0.60534982 0.73973725 0.01193791 0.85482394 0.51389929
 0.87719577 0.61980527 0.98260251 0.07691083 0.8132868  0.1384605
 0.10742916 0.92030772 0.43215508 0.11308878 0.70560992 0.02262

### Problem 6: Create a Placeholder for Missing Data

* Task: You are creating a dataset with 50 rows and 5 columns, but the data is not yet available. Initialize this dataset as a NumPy array where every value is -1 to indicate missing data.

* Test Case:

* Input: None

* Expected Output: A 50x5 NumPy array where every element is -1.

In [14]:
dataset = np.full((50,5),-1)
print(dataset)

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


### Problem 7: Generate Timestamps

* Task: You need to generate 10 evenly spaced time points for a measurement that runs from 0 seconds to 60 seconds. Create the array of these time points.

* Test Case:

* Input: None

* Expected Output: [ 0. , 6.66..., 13.33..., ..., 53.33..., 60. ]

In [15]:
arr = np.linspace(0,60,10)
print(arr)

[ 0.          6.66666667 13.33333333 20.         26.66666667 33.33333333
 40.         46.66666667 53.33333333 60.        ]


### Problem 8: Simulate Survey Responses

* Task: You are simulating responses for a survey question with a rating scale of 1 to 5. Generate a NumPy array of 200 random integer responses.

* Test Case:

* Input: None

* Expected Output: A 1D NumPy array of size 200 containing random integers between 1 and 5 (inclusive).

In [17]:
random_int = np.random.randint(1,6,200)
print(random_int)

[2 5 4 1 4 4 2 3 3 3 5 3 1 3 5 5 4 1 2 3 5 1 2 2 5 3 2 1 3 5 3 4 4 3 2 5 1
 4 2 1 5 4 3 3 3 5 2 4 4 4 3 5 3 2 1 2 2 1 5 2 5 4 4 1 3 4 4 3 3 3 4 4 1 3
 3 4 5 5 2 2 2 1 1 3 2 2 5 2 2 1 3 5 3 1 5 2 2 2 2 3 2 5 5 4 3 2 2 5 2 4 1
 2 1 3 2 4 1 4 3 4 5 1 5 2 5 3 3 3 1 2 4 3 5 1 5 2 3 4 2 2 2 2 3 3 5 3 4 1
 5 3 2 1 3 1 4 4 3 3 4 2 5 5 4 4 4 4 3 3 5 4 1 2 5 1 4 1 5 3 3 2 4 2 3 1 4
 5 2 5 2 5 2 2 2 1 1 2 4 2 1 4]


### Problem 9: Create a Feature Engineering Matrix

* Task: In some machine learning models, you need a special matrix (an identity matrix) for calculations. Create a 6x6 identity matrix and then inspect its shape and data type.

* Test Case:

* Input: None

* Expected Output:

* An array that is a 6x6 identity matrix (1.0 on the diagonal, 0.0 elsewhere).

* Shape: (6, 6)

* Dtype: float64

In [20]:
identity = np.eye((6))
print(identity.shape)
print(identity.dtype)

(6, 6)
float64


### Problem 10: Initialize a 3D Data Cube

* Task: In scientific computing, you might work with 3D data. Create a 3x4x5 NumPy array (a data "cube") and initialize it entirely with zeros. Then, inspect its shape, number of dimensions, and total size.

* Test Case:

* Input: None

* Expected Output:

* Shape: (3, 4, 5)

* Ndim: 3

* Size: 60

In [22]:
cube = np.full((3,4,5),0)
print(cube.shape)
print(cube.ndim)
print(cube.size)

(3, 4, 5)
3
60


# Day2
## problems on indexing and slicing

### Problem 1: Select a Specific Data Point

* Task: You have a 1D NumPy array representing daily sales. Your task is to extract the sales figure for the third day and the last day.

* Test Case:
* Input: daily_sales = np.array([150, 200, 175, 220, 210, 190, 180])
* Expected Output:
* Third day sales: 175
* Last day sales: 180

In [2]:
daily_sales = np.array([150, 200, 175, 220, 210, 190, 180])
print(daily_sales[2])
print(daily_sales[-1])

175
180


### Problem 2: Get a Week's Worth of Data
* Task: From a 1D array of monthly temperature readings, extract the data for the second week (indices 7 to 13, inclusive).
* Test Case:
* Input: temperatures = np.array([22, 23, 21, 24, 25, 26, 24, 25, 27, 28, 26, 25, 24, 23, ...]) (imagine a long array)
* Expected Output: An array containing the 7 temperatures from index 7 up to and including index 13.

In [4]:
temperatures = np.array([22, 23, 21, 24, 25, 26, 24, 25, 27, 28, 26, 25, 24, 23,24,25,26,28,29
                        ,30,31,32,33,34,35])
print(temperatures[7:14])

[25 27 28 26 25 24 23]


### Problem 3: Accessing a Cell in a Dataset
* Task: You have a 2D array representing a small dataset where rows are users and columns are [Age, Score]. Extract the score of the second user.
* Test Case:
* Input: user_data = np.array([[25, 88], [32, 95], [45, 76]])
* Expected Output: 95

In [6]:
user_data = np.array([[25, 88], [32, 95], [45, 76]])
print(user_data[1,1])

95


### Problem 4: Extract a Column of Data
* Task: From the user_data 2D array (rows=users, columns=[Age, Score, ItemsPurchased]), extract all the scores into a new 1D array.
* Test Case:
* Input: user_data = np.array([[25, 88, 5], [32, 95, 8], [45, 76, 3]])
* Expected Output: [88, 95, 76]

In [34]:
user_data = np.array([[25, 88, 5], [32, 95, 8], [45, 76, 3]])
print(user_data[:,1])

[88 95 76]


### Problem 6: Reverse the Order of Data
* Task: You are given a 1D array of stock prices recorded throughout the day. Reverse the array so that the latest price is first.
* Test Case:
* Input: prices = np.array([150.1, 150.5, 151.2, 150.8])
* Expected Output: [150.8, 151.2, 150.5, 150.1]

In [12]:
prices = np.array([150.1, 150.5, 151.2, 150.8])
print(prices[::-1])

[150.8 151.2 150.5 150.1]


### Problem 7: Get Every Other Data Point
* Task: From a long series of sensor readings, extract every 10th reading to get a down-sampled overview of the data.
* Test Case:
* Input: sensor_readings = np.arange(100)
* Expected Output: [ 0 10 20 30 40 50 60 70 80 90]

In [17]:
sensor_readings = np.arange(0,100,10)
print(sensor_readings)

[ 0 10 20 30 40 50 60 70 80 90]


### Problem 8: Conditional Filtering (Boolean Indexing)
* Task: You have an array of exam scores. Create a new array containing only the scores that are 80 or higher.
* Test Case:
* Input: scores = np.array([75, 92, 88, 64, 81, 79, 95, 80])
* Expected Output: [92, 88, 81, 95, 80]

In [19]:
scores = np.array([75, 92, 88, 64, 81, 79, 95, 80])
print(scores[scores>=80])

[92 88 81 95 80]


### Problem 9: Selecting Specific Rows and Columns
* Task: From a 2D dataset, extract the data for the 1st, 3rd, and 4th rows, but only for the 1st and last columns.
* Test Case:
* nput: dataset = np.arange(25).reshape(5, 5)
* Expected Output:

*   [[ 0  4]
     [10 14]
     [15 19]]

In [31]:
dataset = np.arange(25).reshape(5, 5)
# print(f"dataset: \n {dataset}")
selected = dataset[[0, 2, 3], :][:, [0, 4]]
print(selected)


[[ 0  4]
 [10 14]
 [15 19]]


### Problem 10: Modifying Data Based on a Condition
* Task: You have a dataset of sensor readings, but some readings are invalid (represented as negative numbers). Create a new version of the dataset where all negative readings are replaced with 0.
* Test Case:
* Input: readings = np.array([[10, 12, -5], [15, -2, 18], [20, 22, 25]])
* Expected Output:

* [[10 12  0]
   [15  0 18]
   [20 22 25]]

In [43]:
readings = np.array([[10, 12, -5], [15, -2, 18], [20, 22, 25]])
readings[readings < 0]=0
print(readings)

[[10 12  0]
 [15  0 18]
 [20 22 25]]


## problems on copy vs view

### Problem 1: Modifying a Data Slice
* Task: You have a 1D NumPy array representing sensor readings over 10 seconds. You create a slice containing the first 5 seconds of data and set all its values to 0 to represent a sensor reset. Predict the final state of the original 10-second array.
* Test Case:
* Input: readings = np.arange(10)
* Action: morning_readings = readings[0:5], then morning_readings[:] = 0
* Question: What will the readings array look like after these actions?

In [44]:
readings = np.arange(10)
morning_readings = readings[0:5]
morning_readings[:] = 0
print(f"morning_readings: {morning_readings}")
print(f"readings: {readings}")

morning_readings: [0 0 0 0 0]
readings: [0 0 0 0 0 5 6 7 8 9]


### Problem 2: Creating a Safe Backup
* Task: You have an array of customer scores. You need to create a separate, independent backup of this array before you perform experimental modifications on the backup. How do you create this backup to ensure the original array is never changed?
* Test Case:
* Input: scores = np.array([88, 92, 75, 100, 64])
* Action: Create a backup_scores array and modify its first element to 0.
* Question: Describe the function you would use. What will the scores array and the backup_scores array look like after the modification?

In [46]:
scores = np.array([88, 92, 75, 100, 64])
backup_scores= scores.copy()
backup_scores[0]= 100
print(f"scores: {scores}")
print(f"backup_scores: {backup_scores}")

scores: [ 88  92  75 100  64]
backup_scores: [100  92  75 100  64]


### Problem 3: Checking for Data Ownership
* Task: You are given a main dataset and two subsets, subset_A and subset_B. One is a view and one is a copy. Describe how you would use the .base attribute to determine which subset, if modified, would alter the main_dataset.
* Test Case:
* Input:
* main_dataset = np.arange(20)
* subset_A = main_dataset[5:10]
* subset_B = main_dataset.copy()
* Question: What would subset_A.base and subset_B.base return? Which one is safe to modify without affecting main_dataset?

In [47]:
main_dataset = np.arange(20)
subset_A = main_dataset[5:10]
subset_B = main_dataset.copy()
print(subset_A.base)
print(subset_B.base)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
None


### Problem 4: Reshaping for Analysis
* Task: You have a 1D array of 12 monthly sales figures. You reshape this into a 4x3 array to analyze quarterly data. You then find a data entry error in the first month of the first quarter and update it to 500 in the reshaped array. Predict the final state of the original 1D monthly sales array.
* Test Case:
* Input: monthly_sales = np.array([100, 120, 150, 130, 140, 160, 110, 130, 170, 150, 180, 200])
* Action: quarterly_sales = monthly_sales.reshape(4, 3), then quarterly_sales[0, 0] = 500
* Question: What will the monthly_sales array look like after this?

In [48]:
monthly_sales = np.array([100, 120, 150, 130, 140, 160, 110, 130, 170, 150, 180, 200])
quarterly_sales = monthly_sales.reshape(4, 3)
quarterly_sales[0, 0] = 500
print(monthly_sales)
print(quarterly_sales)

[500 120 150 130 140 160 110 130 170 150 180 200]
[[500 120 150]
 [130 140 160]
 [110 130 170]
 [150 180 200]]


### Problem 5: Slicing vs. Advanced Indexing
* Task: You have a dataset of 10 user IDs. You perform two experiments:
* Create group1 by slicing the first 4 users.
* Create group2 by selecting users at specific indices [0, 3, 5, 7]. You then set the first element of both group1 and group2 to 99. Predict the final state of the original user_ids array after both operations.
* Test Case:
* **Input**: user_ids = np.arange(10, 20)
* **Action 1**: group1 = user_ids[0:4], then group1[0] = 99

* **Action 2**: group2 = user_ids[[0, 3, 5, 7]], then group2[0] = 99
* Question: What is the final value of the user_ids array? Explain why the two actions produce different results on the original array.

In [52]:
user_ids = np.arange(10, 20)
group2 = user_ids[[0, 3, 5, 7]]
group2[0] = 99
print(f"group2 result: {user_ids}") # its creates a copy 
group1 = user_ids[0:4]
group1[0] = 99
print(f"group1 result: {user_ids}")  # its create a view


group2 result: [10 11 12 13 14 15 16 17 18 19]
group1 result: [99 11 12 13 14 15 16 17 18 19]
