# Numpy


### What is NumPy?

* NumPy stands for **'Numerical Python.'**
- NumPy is a Python library used for fast math with numbers.
- **It has a special data type called an array** (ndarray) that stores lots of numbers together.
- **NumPy arrays are faster and use less memory** than Python lists for numerical work.
- **It is used in data science, machine learning, and scientific research.**
- **NumPy makes it easy to do math on entire lists of numbers at once.**


### Why is NumPy faster than Python lists?
- **Memory Layout**: NumPy arrays store all their data in one big block (contiguous memory), while Python lists are scattered in memory.​

- **Data Types**: NumPy arrays use the same data type for all elements. Python lists can mix anything (numbers, strings, objects), which makes them slower for math.​

- **Underlying Code**: NumPy uses optimized code written in C, which makes operations much faster than Python’s built-in loops.​

- Example: Multiplying two million numbers is often 10–50 times faster with NumPy than with lists.​

- **Vectorized Operations**: In NumPy you can apply math to all elements at once (e.g., array1 * array2), instead of looping through each item.

## creating Arrays

### 1. From a List
* Convert a Python list to a NumPy array.

In [1]:
import numpy as np

In [2]:
arr_list = np.array([1, 2, 3])
print(arr_list)

[1 2 3]


### 1.1 From a Nested List
*  List of lists forms rows of a 2D array.

### 2. From a Tuple
* Convert a Python tuple to a NumPy array.

In [16]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)


[[1 2 3]
 [4 5 6]]


In [3]:
arr_tuple = np.array((4, 5, 6))
print(arr_tuple)


[4 5 6]


### 3. From a Set
* Convert a Python set to a NumPy array (order may vary).

In [4]:
arr_set = np.array({7, 8, 9})
print(arr_set) #  (order may change)


{8, 9, 7}


### 4. From a Dictionary
* Create a NumPy array from a dictionary’s keys or values or items.

In [7]:
d = {'a': 1, 'b': 2, 'c': 3}
arr_keys = np.array(list(d.keys()))
arr_values = np.array(list(d.values()))
arr_items = np.array(list(d.items()))
print(arr_keys)
print(arr_values)
print(arr_items)


['a' 'b' 'c']
[1 2 3]
[['a' '1']
 ['b' '2']
 ['c' '3']]


### 5. Arrays filled with zeros
* Note: Creates arrays filled with 0.0 (float by default)

In [6]:
arr2 = np.zeros(5)          # 1D array
arr3 = np.zeros((2, 3))     # 2D array (2 rows, 3 columns)
print(arr2)
print(arr3)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


### 6. Arrays filled with ones
* Note: Creates arrays filled with 1.0 (float by default)

In [8]:
arr4 = np.ones(4)
arr5 = np.ones((3, 2))
print(arr4)
print(arr5)


[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


### 7. Arrays filled with custom values
* Note: Fill array with any specific value you want

In [9]:
arr6 = np.full(5, 99)       # Fill with 99
arr7 = np.full((2, 2), 7)   # 2x2 array filled with 7
print(arr6)
print(arr7)


[99 99 99 99 99]
[[7 7]
 [7 7]]


### 8. Range of numbers (like Python range)
* Note: Creates sequence of numbers with start, stop, step

In [10]:
arr8 = np.arange(0, 10, 2)  # start=0, stop=10, step=2
arr9 = np.arange(5)         # Just stop=5 (start=0, step=1)
print(arr8)
print(arr9)


[0 2 4 6 8]
[0 1 2 3 4]


### 9. Evenly spaced numbers
* Note: Creates specific number of evenly spaced values between start and stop

In [11]:
arr10 = np.linspace(1, 5, 4)    # 4 numbers between 1 and 5
arr11 = np.linspace(0, 1, 6)    # 6 numbers between 0 and 1
print(arr10)
print(arr11)


[1.         2.33333333 3.66666667 5.        ]
[0.  0.2 0.4 0.6 0.8 1. ]


### 10. Identity matrix
* Note: Creates square matrix with 1s on diagonal, 0s elsewhere

In [12]:
arr12 = np.eye(3)           # 3x3 identity matrix
arr13 = np.identity(4)      # 4x4 identity matrix
print(arr12)
print(arr13)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 11. Random numbers (0 to 1)
* Note: Creates random floating-point numbers between 0 and 1

In [13]:
arr14 = np.random.rand(3)       # 1D array with 3 random numbers
arr15 = np.random.rand(2, 3)    # 2x3 array with random numbers
print(arr14)
print(arr15)


[0.67672802 0.57155503 0.24755287]
[[0.2151532  0.54922023 0.28272642]
 [0.23317659 0.36020698 0.01232097]]


### 9. Random integers
* Note: Creates random integers within specified range

In [14]:
arr16 = np.random.randint(1, 10, 5)     # 5 random ints from 1-9
arr17 = np.random.randint(0, 5, (2, 3)) # 2x3 array, ints from 0-4
print(arr16)
print(arr17)


[9 6 1 2 4]
[[3 3 1]
 [0 2 4]]


## NumPy Array Properties

### shape
*  Tells the dimensions of the array (rows, columns)

In [17]:

arr1 = np.array([1, 2, 3])
print(arr1.shape)  

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.shape) 

arr3 = np.zeros((4, 5, 2))
print(arr3.shape) 


(3,)
(2, 3)
(4, 5, 2)


###  ndim
* Tells the number of dimensions (axes).



In [18]:
print(arr1.ndim)  
print(arr2.ndim)  
print(arr3.ndim)  


1
2
3


###  size
* Tells total number of elements in the array.

In [20]:
print(arr1.size)  
print(arr2.size)  
print(arr3.size)  


3
6
40


### dtype
* Tells the data type of array elements.

In [22]:
arr4 = np.array([1, 2, 3])
print(arr4.dtype)  # int64 (or int32)

arr5 = np.array([1.0, 2.5, 3.1])
print(arr5.dtype)  # float64

arr6 = np.array([True, False, True])
print(arr6.dtype)  # bool

arr7 = np.array([1, 2, 3], dtype='float32')
print(arr7.dtype)  # float32


int64
float64
bool
float32


### Indexing

* Indexing means accessing individual elements using their position (index) in a NumPy array. In NumPy, indexing starts at 0, just like Python lists. You can use positive and negative indices:

* **Positive indexing**: Starts from 0 and increases forward.

* **Negative indexing**: Starts from -1 (last element), -2 (second last), etc.

#### 1D Array:

In [2]:

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])    # Output: 10 (first element)
print(arr[2])    # Output: 30 (third element)
print(arr[-1])   # Output: 50 (last element)
print(arr[-3])   # Output: 30 (third from last)


10
30
50
30


#### 2D Array:

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[0, 1])   # Output: 2 (first row, second column)
print(a[1, -1])  # Output: 6 (second row, last column)


2
6


###  Slicing
Slicing extracts a subset (range or section) of elements from an array. 
* It uses the syntax: **array[start:stop:step]**
* start: index to begin (inclusive)
* stop: index to end (exclusive)
* step: interval between selections (default 1* *

#### 1D Array Slicing

In [4]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[1:4])      # Output: [20 30 40] (indexes 1,2,3)
print(arr[:3])       # Output: [10 20 30] (start to index 2)
print(arr[3:])       # Output: [40 50 60 70] (index 3 to end)
print(arr[1:6:2])    # Output: [20 40 60] (every second element from index 1 to 5)


[20 30 40]
[10 20 30]
[40 50 60 70]
[20 40 60]


#### Negative Index and Slicing
* Negative indices count from the array's end.

In [5]:
print(arr[-4:-1])     # Output: [40 50 60] (from 4th from end to last-1)
print(arr[::-1])      # Output: [70 60 50 40 30 20 10] (reversed array)
print(arr[-1:-6:-2])  # Output: [70 50 30] (from end backwards, every 2nd element)


[40 50 60]
[70 60 50 40 30 20 10]
[70 50 30]


### 2D Array Slicing and Indexing
* For 2D arrays, provide slices for rows and columns:
*   **array[row_start : row_end, col_start : col_end]**

In [7]:
arr2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# Slicing first two rows, columns 1 to 3
print(arr2d[0:2, 1:3])   # Output: [[2 3]
                           #         [6 7]]
# All rows, only column 2
print(arr2d[:, 2])        # Output: [ 3  7 11]
# Last two rows and last column
print(arr2d[-2:, -1])     # Output: [ 8 12]


[[2 3]
 [6 7]]
[ 3  7 11]
[ 8 12]


#### Negative Slicing in 2D Arrays:

In [8]:
# Reverse rows
print(arr2d[::-1, :])     # Output: rows reversed
# Reverse columns
print(arr2d[:, ::-1])     # Output: columns reversed


[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


### Advanced Indexing
#### Integer Array Indexing
* Select specific elements using arrays of indices.

In [9]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([3, 1, 4])
print(arr[indices])  # Output: [40 20 50]


[40 20 50]


#### Boolean Indexing
* Select elements based on conditional checks.

In [11]:
arr = np.array([10, 25, 30, 45, 50])
mask = arr > 30
print(mask)         # Output: [False False False  True  True]
print(arr[mask])    # Output: [45 50]


[False False False  True  True]
[45 50]


## NumPy Array Copy vs View 

### 1. What is a Copy in NumPy?
* A copy means a new array object with its own separate data and memory location. When you modify the copy, the original array remains unchanged.

➤ Key Points
* A copy owns its data.
* Changes made to the copy do not affect the original array.
* It consumes more memory, as data is duplicated.
  
 ➤ Method
* Use **np.copy()** or **.copy()** to create a copy.
  
 #### Example 1 — Modifying a Copy

In [14]:
arr = np.array([1, 2, 3, 4, 5])
copy_arr = arr.copy()

copy_arr[0] = 99  # Modify the copy

# Changes in copy_arr do NOT affect arr.

print("Original Array:", arr)
print("Copied Array:", copy_arr)


Original Array: [1 2 3 4 5]
Copied Array: [99  2  3  4  5]


#### Example 2 — Copying a 2D Array

In [17]:
matrix = np.array([[1, 2], [3, 4]])
copy_matrix = matrix.copy()


copy_matrix[0, 0] = 99

# Both matrices are independent
print("Original Matrix:\n", matrix)
print("Copied Matrix:\n", copy_matrix)


Original Matrix:
 [[1 2]
 [3 4]]
Copied Matrix:
 [[99  2]
 [ 3  4]]


 ### 2. What is a View in NumPy?
* A view means a different object looking at the same data buffer. When you change one, the other is also affected.

➤ Key Points
* A view shares data with the original array.
* Changing the view also changes the original array.
*It is memory-efficient (no data duplication).
    
➤ Method
* Use **.view()** or **slicing (:)** to create a view.

####  Example 3 — Modifying a View


In [19]:
arr = np.array([10, 20, 30, 40, 50])
view_arr = arr.view()

view_arr[1] = 99  # modify the view

 # Changes in view_arr are also reflected in arr because they share the same data memory.
print("Original Array:", arr)
print("View Array:", view_arr)


Original Array: [10 99 30 40 50]
View Array: [10 99 30 40 50]


#### Example 4 — 2D Array View

In [20]:
matrix = np.array([[1, 2], [3, 4]])
view_matrix = matrix.view()

matrix[1, 1] = 99

# Any change reflects in both, since memory is shared.
print("Original:\n", matrix)
print("View:\n", view_matrix)


Original:
 [[ 1  2]
 [ 3 99]]
View:
 [[ 1  2]
 [ 3 99]]


 ### 3. How to Check if an Array is a Copy or a View
* NumPy provides the .base attribute.
* If **arr.base is None**, it’s a copy (owns data).
*If **arr.base returns another array**, it’s a view (shares data).

#### Example 5 — Using .base

In [21]:
arr = np.array([1, 2, 3, 4, 5])
copy_arr = arr.copy()
view_arr = arr.view()

print(copy_arr.base)  # Output: None (copy)
print(view_arr.base)  # Output: Original array (view)


None
[1 2 3 4 5]


### 4. Slicing Produces Views
* Slicing an array usually creates a view, not a copy.

####  Example 6 — Slice Behavior

In [23]:
a = np.array([1, 2, 3, 4, 5])
sub_a = a[1:4]
sub_a[0] = 99

# Sliced arrays share memory — changes reflect in both.
print("Original Array:", a)
print("Sliced View:", sub_a)


Original Array: [ 1 99  3  4  5]
Sliced View: [99  3  4]


### **Note**: Some operations like advanced indexing or arithmetic may create copies, not views.

### 6. Advanced Example — Reshaping Arrays
* Reshaping can create views.

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)

reshaped[0, 0] = 99
 
# Changes in reshaped affect original.
print("Original Array:", arr)
print("Reshaped View:\n", reshaped)


Original Array: [99  2  3  4  5  6]
Reshaped View:
 [[99  2  3]
 [ 4  5  6]]


### But: Certain operations like fancy indexing create copies, not views:

In [25]:
arr = np.array([10, 20, 30, 40])
copy_via_index = arr[[0, 2]]  # fancy indexing
copy_via_index[0] = 99

# The original remains unaffected (deep copy behavior).
print("Original Array:", arr)
print("Indexed Array:", copy_via_index)


Original Array: [10 20 30 40]
Indexed Array: [99 30]


## Quick Memory Check Rule
* **If you only want to read or temporarily rearrange data — use a View.**
* **If you need an independent dataset — use a Copy.**